version: '3.8'

services:
  wordpress:
    image: wp-custom-image
    container_name: wp_wordpress
    ports:
      - "8080:80"
      - "3307:3306"
    volumes:
      - wp-data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped

volumes:
  wp-data: